spring:
  datasource: #如果mysql在本机，就换成127.0.0.1:mysql端口号，即：jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/paysystem?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root #数据库用户名
    password: root #数据库密码
  thymeleaf:
    cache: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
server:
  port: 8000 #运行端口
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #如果数据库数据更新不及时关闭此选项
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
